server:
  port: ${PORT:9004}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL}/account
  application:
    name: ACCOUNT-SERVICE

app:
  mqtt:
    broker: ${MQTT_BROKER}
    username: ${MQTT_USERNAME}
    clientId: ${spring.application.name}
    password: ${MQTT_PASSWORD}
